module.exports = {
	Field: require('../LocationField'),
	Filter: require('../LocationFilter'),
	readme: require('fs').readFileSync('./fields/types/location/Readme.md', 'utf8'),
	section: 'Text',
	spec: {
		label: 'Location',
		path: 'location',
		paths: {
			country: 'location.country',
			geo: 'location.geo',
			geo_lat: 'location.geo_lat',
			geo_lng: 'location.geo_lng',
			improve: 'location.improve',
			name: 'location.name',
			overwrite: 'location.overwrite',
			postcode: 'location.postcode',
			serialised: 'location.serialised',
			state: 'location.state',
			street_address: 'location.street_address',
			municipality: 'location.municipality',
			neighborhood: 'location.neighborhood',
		},
		value: {
			country: null,
			postcode: null,
			state: null,
			street_address: null,
			neighborhood: null,
		},
	},
};
