module.exports = {
	Field: require('../LocationField'),
	Filter: require('../LocationFilter'),
	readme: require('fs').readFileSync('./fields/types/location/Readme.md', 'utf8'),
	section: 'Text',
	spec: {
		label: 'Location',
		path: 'location',
		paths: {
			country: 'location.country',
			geo: 'location.geo',
			geo_lat: 'location.geo_lat',
			geo_lng: 'location.geo_lng',
			improve: 'location.improve',
			name: 'location.name',
			overwrite: 'location.overwrite',
			postal_code: 'location.postal_code',
			state: 'location.state',
			street1: 'location.street1',
			street2: 'location.street2',
			suburb: 'location.suburb',
		},
		value: {
			country: null,
			postal_code: null,
			state: null,
			street1: null,
			suburb: null,
		},
	},
};
